# Generated by Django 6.0.1 on 2026-01-19 17:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_hotel_city_alter_hotel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+996', max_length=128, region='KG'),
        ),
    ]
